use snekkja::{AisMessage, Parser};

fn parse(sentence: &[u8]) -> AisMessage {
    let mut parser = Parser::default();
    parser
        .parse(sentence)
        .expect("parse failed")
        .message
        .expect("no message")
}

// --- Type 1 ---

#[test]
fn type1_french_vessel() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,13HOI:0P0000VOHLCnHQKwvL05Ip,0*23"));
}
#[test]
fn type1_mediterranean() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,13eaJF0P00Qd388Eew6aagvH85Ip,0*45"));
}
#[test]
fn type1_canadian() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,14eGrSPP00ncMJTO5C6aBwvP2D0?,0*7A"));
}
#[test]
fn type1_caribbean() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,15MrVH0000KH<:V:NtBLoqFP2H9:,0*2F"));
}
#[test]
fn type1_mississippi() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,15N9NLPP01IS<RFF7fLVmgvN00Rv,0*7F"));
}
#[test]
fn type1_belgian_port() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,133hGvP0000CjLHMG0u==:VN05Ip,0*61"));
}
#[test]
fn type1_korean() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,16S`2cPP00a3UF6EKT@2:?vOr0S2,0*00"));
}
#[test]
fn type1_st_lawrence() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,14eGKMhP00rkraHJPivPFwvL0<0<,0*23"));
}
#[test]
fn type1_bohai_sea() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,16:=?;0P00`SstvFnFbeGH6L088h,0*44"));
}
#[test]
fn type1_yangtze_underway() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,169a:nP01g`hm4pB7:E0;@0L088i,0*5E"));
}

// --- Type 2 ---

#[test]
fn type2_barbados() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,24SaQh500G0Cu7nMErpJ680N0@9C,0*3F"));
}
#[test]
fn type2_finnish() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,23L?MH001UP>QqDMIOlC7BHN05Ip,0*17"));
}
#[test]
fn type2_dutch_moored() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,23aFfl0P00PCR>4MEBBP0?vN20S<,0*23"));
}
#[test]
fn type2_scheldt_inbound() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,23NCqt5OiL0>Ve4MI0rtEb0P2@9G,0*03"));
}
#[test]
fn type2_north_sea() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,239a=5RP0wPBGTpMKnQP`gv<R<1t,0*4C"));
}

// --- Type 3 ---

#[test]
fn type3_gulf_of_mexico() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,35Mtp?0016J5ohD?ofRWSF2R0000,0*28"));
}
#[test]
fn type3_rotterdam() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,33aDqfhP00PD2OnMDdF@QOvN205A,0*13"));
}
#[test]
fn type3_pearl_river() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,36:RS:001?87bnt=:rq68TnN00nh,0*20"));
}
#[test]
fn type3_yangtze_slow() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,369AM`1P028d;40Aohk1EgvN2000,0*72"));
}
#[test]
fn type3_tokyo_bay() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,33bi=B5wP0awIEJDAdSEoVLN0000,0*6C"));
}

// --- Type 4 ---

#[test]
fn type4_denmark() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,4020ssAuho;N?PeNwjOAp<70089A,0*09"));
}
#[test]
fn type4_canary_islands() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,4028j=1uho;N>Npi9j?wtk700@8a,0*09"));
}
#[test]
fn type4_ligurian_sea() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,402FhaQuho6Nj0dsn4I=k<i004ip,0*77"));
}
#[test]
fn type4_south_china_sea() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,403tAEiuho;N?89E5:<nomQ00<8u,0*08"));
}
#[test]
fn type4_puget_sound() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,4h3OvjAuho;N>o=cf0Knevo00l3;,0*38"));
}
#[test]
fn type4_valencia() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,4028j:Quho;MgOvPkdFl:VG000S:,0*74"));
}
#[test]
fn type4_norway_no_timestamp() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,402M4L@000Htt12>B0VPVH700`Ct,0*2A"));
}

// --- Type 18 ---

#[test]
fn type18_class_b_channel_b() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,B43JRq00LhTWc5VejDI>wwWUoP06,0*29"));
}
#[test]
fn type18_class_b_display() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,B6:io8@0=21k=`3C:eDJSww4SP00,0*68"));
}
#[test]
fn type18_class_b_channel_a() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,B6:Qno000279<OSPdw`03wWUoP06,0*78"));
}

// --- Type 10 ---
// Type 10 sentences generated by scripts/gen_ais.py.

#[test]
fn type10_utc_date_inquiry() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,:1mg=5CcNJ;4,0*04"));
}

// --- Type 11 ---
// Type 11 sentences generated by scripts/gen_ais.py.

#[test]
fn type11_utc_date_response() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,;02?:kQvaL<0N0Bor@N0wh102000,0*74"));
}

// --- Type 12 ---
// Type 12 sentences generated by scripts/gen_ais.py.

#[test]
fn type12_plain_text() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,<1mg=5CcNJ;4@<51C5PB5@?BDPD?P:?2?EB7PDB16693P381>>5<Pik,0*4D"
    ));
}
#[test]
fn type12_retransmitted() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,<1b4N?IawHI:31ED9?>PB5CDB93D54P1B51,0*59"
    ));
}

// --- Type 13 ---
// Type 13 sentences generated by scripts/gen_ais.py.

#[test]
fn type13_one_destination() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,=1mg=5CcNJ;4,0*03"));
}
#[test]
fn type13_two_destinations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,=1mg=5CcNJ;46`Apu@,4*55"));
}

// --- Type 25 ---
// Type 25 sentences generated by scripts/gen_ais.py.

#[test]
fn type25_broadcast_unstructured() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,I1mg=5CNcKsg,0*6D"));
}
#[test]
fn type25_broadcast_structured() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,I1mg=5DB=0420h,4*0D"));
}
#[test]
fn type25_addressed_unstructured() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,I1mg=5KcNJ;7:wP,4*65"));
}
#[test]
fn type25_addressed_structured() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,I1mg=5OcNJ;41@Jg=,0*1A"));
}

// --- Type 23 ---
// Type 23 sentences generated by scripts/gen_ais.py.

#[test]
fn type23_all_mobiles_one_minute() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,G1mg=5@2sPv703Q1oR000000400,2*2A"));
}
#[test]
fn type23_class_b_quiet_time() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,G1mg=5@2sPv703Q1oR200000E80,2*51"));
}

// --- Type 22 ---
// Type 22 sentences generated by scripts/gen_ais.py.

#[test]
fn type22_broadcast_geographic() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,F1mg=5B2N2P05o1t>0723g420000,0*79"));
}
#[test]
fn type22_addressed_mmsi() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,F1mg=5B2N2P?FtlF81b4N?@B0000,0*04"));
}

// --- Type 20 ---
// Type 20 sentences generated by scripts/gen_ais.py.

#[test]
fn type20_one_reservation() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,D1mg=5@6A6fp,2*44"));
}
#[test]
fn type20_two_reservations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,D1mg=5@6A6fp<Pc6D,2*39"));
}
#[test]
fn type20_three_reservations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,D1mg=5@6A6fp<Pc6DBhOMh,2*79"));
}
#[test]
fn type20_four_reservations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,D1mg=5@6A6fp<Pc6DBhOMhI0lGL,2*67"));
}

// --- Type 15 ---
// Type 15 sentences generated by scripts/gen_ais.py.

#[test]
fn type15_one_station_one_type() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,?1mg=5CcNJ;4<00,2*3F"));
}
#[test]
fn type15_one_station_two_types() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,?1mg=5CcNJ;4<005?`,0*57"));
}
#[test]
fn type15_two_stations_one_type_each() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,?1mg=5CcNJ;4<000001b4N?@Au0,2*5D"));
}
#[test]
fn type15_two_stations_two_plus_one() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,?1mg=5CcNJ;4<005?`1b4N?@Au0,2*07"));
}

// --- Type 16 ---
// Type 16 sentences generated by scripts/gen_ais.py.

#[test]
fn type16_single_assignment() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,@1mg=5CcNJ;4<P00,0*12"));
}
#[test]
fn type16_single_assignment_nonzero_increment() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,@1mg=5CcNJ;4<P20,0*10"));
}
#[test]
fn type16_dual_assignment() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,@1mg=5CcNJ;4<P01b4N?AT00,0*21"));
}

// --- Type 9 ---
// Type 9 is rare in the wild (SAR aircraft only); sentences generated by scripts/gen_ais.py.

#[test]
fn type9_airborne_known_position() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,91mg=5Eo3rPBor@N0wh<CWP04000,0*25"));
}
#[test]
fn type9_unknown_altitude_and_speed() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,9>eq`dOwwwJerP0GBrh3Q;@00000,0*02"));
}
#[test]
fn type9_dte_not_ready_assigned() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,91b4N?Au2l9wM6@DJv6720028000,0*67"));
}

// --- Type 7 ---
// Type 7 is rare in the wild (shore-station ack only); sentences generated by scripts/gen_ais.py.

#[test]
fn type7_one_destination() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,71mg=5CcNJ;4,0*09"));
}
#[test]
fn type7_two_destinations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,71mg=5CcNJ;46`Apu@,4*5F"));
}
#[test]
fn type7_three_destinations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,71mg=5CcNJ;46`ApuFWuQT`,2*18"));
}
#[test]
fn type7_four_destinations() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,71mg=5CcNJ;46`ApuFWuQTbqMa>O,0*34"));
}

// --- Type 21 ---

#[test]
fn type21_aton_buoy() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,E0000ChcFstP000000000000000?iM91:RGuH00003RP10,4*3F"
    ));
}
#[test]
fn type21_aton_lighthouse() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,E>j9dhiQ0a2Hh;TW230a6h72P00@=igf?TQA000003vP10,4*54"
    ));
}
#[test]
fn type21_aton_name_extension() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,E>q7CUL6RTh=47bh;PW@Ht@40Wh4@Jwp7:sv@20@@@T7HQ1CQp1U@0,4*1C"
    ));
}
#[test]
fn type21_aton_name_extension_2() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,B,E>q7CQL`bPW@=47bh;PW@Jh40Wh4?n8P76BG020@@@RWHQ1CQp1U@0,4*76"
    ));
}

// --- Type 14 ---
// Type 14 sentences generated by scripts/gen_ais.py.

#[test]
fn type14_navigation_warning() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,>1mg=5@p5HTL5@Ttp4j1L58pTpN1<Pt4hTpN18E0u9@DB0Tr0<P4ppDh,2*56"
    ));
}
#[test]
fn type14_distress_broadcast() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,>52T=1h4hj1<PU1>0l5T@5V1HE=<Dj04M8uDpB10u<U@Ttr3G8r333@D,2*65"
    ));
}

// --- Type 8 ---
// Type 8 sentences generated by scripts/gen_ais.py.

#[test]
fn type8_header_only() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,81mg=5@0Gh,4*76"));
}
#[test]
fn type8_with_payload() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,81mg=5@0Buregft,2*0A"));
}
#[test]
fn type8_us_seaway() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,852T=1iKP@420h@5,0*58"));
}

// --- Type 6 ---
// Type 6 sentences generated by scripts/gen_ais.py.

#[test]
fn type6_header_only() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,61mg=5CcNJ;404h,2*66"));
}
#[test]
fn type6_with_payload_retransmitted() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,61mg=5KcNJ;605WNcKsg,0*22"));
}
#[test]
fn type6_us_local_extension() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,652T=1hMKkADFp410P<4,0*14"));
}

// --- Type 19 ---
// Type 19 sentences generated by scripts/gen_ais.py.

#[test]
fn type19_vessel_underway() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,C52T=1h0@N`pUL5P4l1kmKg0N6:2M0:hPHNT:U111110N1T52230,0*5D"
    ));
}
#[test]
fn type19_not_available_fields() {
    insta::assert_debug_snapshot!(parse(
        b"!AIVDM,1,1,,A,C1mg=5@3wk?8mP=18D3Q3wv0TN``:T82K11111111110S0000000,0*75"
    ));
}

// --- Type 24 ---

#[test]
fn type24_part_a_vessel_name() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,H7P<1>1LPU@D8U8A<0000000000,2*6C"));
}
#[test]
fn type24_part_a_160bit() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,H0HN<8QLTdTpN22222222222223,2*1B"));
}
#[test]
fn type24_part_b_dimensions() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,A,H7P<1>4UB1I0000F=Aqpoo2P2220,0*3A"));
}
#[test]
fn type24_part_b_vendor_model() {
    insta::assert_debug_snapshot!(parse(b"!AIVDM,1,1,,B,H44?BB4lDB1>C1CEC130001@F270,0*04"));
}
